In [1]:
from data_reader.data_reader import DataReader
from data_reader.helpers import locations
diplomas=DataReader(
    path=locations("diplomes"), 
    sheet_name='COM_2012',
    skiprows=16, 
    insee_code=('dr','cr'),
    drop_domtom=True,
    rm_nan=True
).content()

In [2]:
diplomas.head()

,rr,dr,cr,stable,dr19,libgeo,dpx_rec0s1age2_rec1rpop2012,dpx_rec0s1age2_rec2rpop2012,dpx_rec0s2age2_rec1rpop2012,dpx_rec0s2age2_rec2rpop2012,...,dpx_rec4s2age2_rec1rpop2012,dpx_rec4s2age2_rec2rpop2012,dpx_rec5s1age2_rec1rpop2012,dpx_rec5s1age2_rec2rpop2012,dpx_rec5s2age2_rec1rpop2012,dpx_rec5s2age2_rec2rpop2012,dpx_rec6s1age2_rec1rpop2012,dpx_rec6s1age2_rec2rpop2012,dpx_rec6s2age2_rec1rpop2012,dpx_rec6s2age2_rec2rpop2012
insee,,,,,,,,,,,,,,,,,,,,,
01001,84,01,001,1,01,Abergement-Clémenciat,0.000000,51.800000,0.000000,31.876923,...,3.984615,39.846154,3.984615,31.876923,0.000000,39.846154,0.00000,31.876923,0.00000,31.876923
01002,84,01,002,1,01,Abergement-De-Varey,0.000000,4.017094,0.000000,4.017094,...,0.000000,0.000000,4.017094,20.085470,4.017094,20.085470,0.00000,20.085470,0.00000,28.119658
01004,84,01,004,1,01,Ambérieu-En-Bugey,82.967676,776.075301,92.881232,889.899799,...,126.700089,826.537361,57.457376,622.807206,65.179417,609.511394,18.96703,472.038160,48.92151,521.414752
01005,84,01,005,1,01,Ambérieux-En-Dombes,8.128713,105.673267,8.128713,93.480198,...,8.128713,105.673267,4.064356,40.643564,4.064356,69.094059,0.00000,44.707921,0.00000,36.579208
01006,84,01,006,1,01,Ambléon,0.000000,0.000000,0.000000,11.785714,...,0.000000,7.857143,0.000000,3.928571,0.000000,3.928571,0.00000,0.000000,0.00000,0.000000

In [3]:
diplomas[diplomas['dr'].str.contains('97')].dr.unique()

array([], dtype=object)

# Overall look at the file and its documentation :

* This file gives the level of education (in terms of diploma) in each departement or town, for people above 16yr. This is split into two age group (16-24, >= 25)
* The closest point to 2013 is 2012
* Values are not filled for some town, because the town did not exist at that time ((dis)appearance)

### Will need to remove the NaN values

# Quickly check issue of not having 2013 :

In [20]:
referendum = DataReader(
    path=locations("referendum"),
    insee_code=('Code du département','Code de la commune'),
    drop_domtom=True
).content()
referendum.head()

,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Inscrits,Abstentions,Blancs et nuls,Choix A,Choix B
insee,,,,,,,,,
01001,01,AIN,001,L'Abergement-Clémenciat,592,84,9,154,345
01002,01,AIN,002,L'Abergement-de-Varey,215,36,5,66,108
01004,01,AIN,004,Ambérieu-en-Bugey,8205,1698,126,2717,3664
01005,01,AIN,005,Ambérieux-en-Dombes,1152,170,18,280,684
01006,01,AIN,006,Ambléon,105,17,1,35,52

In [6]:
import pandas as pd
full=pd.concat([diplomas,referendum],axis=1)

In [21]:
full[full['rr'].isna()]
full.columns

Index(['rr', 'dr', 'cr', 'stable', 'dr19', 'libgeo',
       'dpx_rec0s1age2_rec1rpop2012', 'dpx_rec0s1age2_rec2rpop2012',
       'dpx_rec0s2age2_rec1rpop2012', 'dpx_rec0s2age2_rec2rpop2012',
       'dpx_rec1s1age2_rec1rpop2012', 'dpx_rec1s1age2_rec2rpop2012',
       'dpx_rec1s2age2_rec1rpop2012', 'dpx_rec1s2age2_rec2rpop2012',
       'dpx_rec2s1age2_rec1rpop2012', 'dpx_rec2s1age2_rec2rpop2012',
       'dpx_rec2s2age2_rec1rpop2012', 'dpx_rec2s2age2_rec2rpop2012',
       'dpx_rec3s1age2_rec1rpop2012', 'dpx_rec3s1age2_rec2rpop2012',
       'dpx_rec3s2age2_rec1rpop2012', 'dpx_rec3s2age2_rec2rpop2012',
       'dpx_rec4s1age2_rec1rpop2012', 'dpx_rec4s1age2_rec2rpop2012',
       'dpx_rec4s2age2_rec1rpop2012', 'dpx_rec4s2age2_rec2rpop2012',
       'dpx_rec5s1age2_rec1rpop2012', 'dpx_rec5s1age2_rec2rpop2012',
       'dpx_rec5s2age2_rec1rpop2012', 'dpx_rec5s2age2_rec2rpop2012',
       'dpx_rec6s1age2_rec1rpop2012', 'dpx_rec6s1age2_rec2rpop2012',
       'dpx_rec6s2age2_rec1rpop2012', 'dpx_rec6s2age2_rec2rpop2012',
       'Code du département', 'Libellé du département', 'Code de la commune',
       'Libellé de la commune', 'Inscrits', 'Abstentions', 'Blancs et nuls',
       'Choix A', 'Choix B'],
      dtype='object')

In [25]:
full[ full['libgeo'] != full['Libellé de la commune'] ][ ['libgeo','Libellé de la commune'] ]

                      libgeo    Libellé de la commune
insee
01001  Abergement-Clémenciat  L'Abergement-Clémenciat
01002    Abergement-De-Varey    L'Abergement-de-Varey
01004      Ambérieu-En-Bugey        Ambérieu-en-Bugey
01005    Ambérieux-En-Dombes      Ambérieux-en-Dombes
01009       Andert-Et-Condon         Andert-et-Condon
...                      ...                      ...
69144                    NaN                  Nuelles
75056                    NaN                    Paris
79353                    NaN                    Vitré
79356                    NaN                Voultegon
88282                    NaN                 Le Magny

[12080 rows x 2 columns]

In [30]:
#full[ (full['libgeo']!=full['Libellé de la commune'])&(full["libgeo"].isna()|full["Libellé de la commune"].isna()) ]

print(f"{sum(full['Libellé de la commune'].isna())} {sum(full['libgeo'].isna())}")

27 21

In [31]:
full[full["Libellé de la commune"].isna()]

,rr,dr,cr,stable,dr19,libgeo,dpx_rec0s1age2_rec1rpop2012,dpx_rec0s1age2_rec2rpop2012,dpx_rec0s2age2_rec1rpop2012,dpx_rec0s2age2_rec2rpop2012,...,dpx_rec6s2age2_rec2rpop2012,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Inscrits,Abstentions,Blancs et nuls,Choix A,Choix B
insee,,,,,,,,,,,,,,,,,,,,,
55039,41.0,55,039,1.0,55,Beaumont-En-Verdunois,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55050,41.0,55,050,1.0,55,Bezonvaux,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55139,41.0,55,139,1.0,55,Cumières-Le-Mort-Homme,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55189,41.0,55,189,1.0,55,Fleury-Devant-Douaumont,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55239,41.0,55,239,1.0,55,Haumont-Près-Samogneux,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
55307,41.0,55,307,1.0,55,Louvemont-Côte-Du-Poivre,0.000000,0.000000,0.000000,0.000000,...,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75101,11.0,75,101,1.0,75,Paris 1er Arrondissement,22.468359,456.989880,20.090311,574.207834,...,3053.430697,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75102,11.0,75,102,1.0,75,Paris 2e Arrondissement,46.962475,933.775749,34.367698,905.608283,...,4030.584107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75103,11.0,75,103,1.0,75,Paris 3e Arrondissement,62.250411,1217.443965,78.722179,1292.360772,...,7022.894459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75104,11.0,75,104,1.0,75,Paris 4e Arrondissement,58.631668,633.418516,48.182236,826.085310,...,5457.230802,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75105,11.0,75,105,1.0,75,Paris 5e Arrondissement,61.024303,1038.704342,49.091055,1333.256706,...,12683.140188,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75106,11.0,75,106,1.0,75,Paris 6e Arrondissement,56.886689,780.389496,35.767319,1341.743337,...,9161.019103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75107,11.0,75,107,1.0,75,Paris 7e Arrondissement,74.109663,1383.178754,46.822190,2024.146404,...,11764.765642,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75108,11.0,75,108,1.0,75,Paris 8e Arrondissement,52.940205,1061.086716,43.604673,1656.760676,...,6905.264132,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75109,11.0,75,109,1.0,75,Paris 9e Arrondissement,119.421458,1921.140007,105.453911,1984.948271,...,11569.366279,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75110,11.0,75,110,1.0,75,Paris 10e Arrondissement,383.881709,4920.093212,222.089729,4727.908471,...,14970.461390,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75111,11.0,75,111,1.0,75,Paris 11e Arrondissement,403.661939,6445.787346,210.511998,6432.021800,...,27770.239269,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75112,11.0,75,112,1.0,75,Paris 12e Arrondissement,301.738824,4569.755435,181.996950,5255.684615,...,23274.147855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75113,11.0,75,113,1.0,75,Paris 13e Arrondissement,554.983038,8767.742701,314.599072,9756.518454,...,26071.229192,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75114,11.0,75,114,1.0,75,Paris 14e Arrondissement,393.062733,4518.178351,267.097077,5373.660869,...,24465.256296,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75115,11.0,75,115,1.0,75,Paris 15e Arrondissement,461.265809,6471.739582,287.862087,8091.717241,...,44506.258381,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75116,11.0,75,116,1.0,75,Paris 16e Arrondissement,229.967202,3925.922267,155.674211,6994.738322,...,30741.145522,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75117,11.0,75,117,1.0,75,Paris 17e Arrondissement,501.701504,6492.491892,337.832515,7468.608390,...,29979.421426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75118,11.0,75,118,1.0,75,Paris 18e Arrondissement,883.388346,12337.315405,536.340272,12189.196701,...,28316.226409,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75119,11.0,75,119,1.0,75,Paris 19e Arrondissement,975.838649,12113.902399,705.994035,13244.767881,...,19855.854689,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75120,11.0,75,120,1.0,75,Paris 20e Arrondissement,967.166857,10775.815766,580.167549,12151.628014,...,23815.783457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76095,28.0,76,095,0.0,76,Bihorel,6.674038,280.884245,14.483145,520.116673,...,665.673721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [32]:
full[full["libgeo"].isna()]

,rr,dr,cr,stable,dr19,libgeo,dpx_rec0s1age2_rec1rpop2012,dpx_rec0s1age2_rec2rpop2012,dpx_rec0s2age2_rec1rpop2012,dpx_rec0s2age2_rec2rpop2012,...,dpx_rec6s2age2_rec2rpop2012,Code du département,Libellé du département,Code de la commune,Libellé de la commune,Inscrits,Abstentions,Blancs et nuls,Choix A,Choix B
insee,,,,,,,,,,,,,,,,,,,,,
05002,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,05,HAUTES ALPES,002,Agnières-en-Dévoluy,268.0,44.0,3.0,80.0,141.0
05020,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,05,HAUTES ALPES,020,Bénévent-et-Charbillac,251.0,29.0,2.0,94.0,126.0
05042,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,05,HAUTES ALPES,042,La Cluse,60.0,4.0,0.0,27.0,29.0
05067,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,05,HAUTES ALPES,067,Les Infournas,30.0,6.0,2.0,10.0,12.0
05138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,05,HAUTES ALPES,138,Saint-Disdier,137.0,30.0,3.0,46.0,58.0
49199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,199,Melay,1217.0,132.0,28.0,342.0,715.0
49213,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,213,Montpollin,134.0,10.0,3.0,35.0,86.0
49245,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,245,Pontigné,198.0,33.0,5.0,48.0,112.0
49303,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,303,Saint-Martin-d'Arcé,545.0,54.0,15.0,208.0,268.0
49372,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,372,Le Vieil-Baugé,995.0,158.0,22.0,317.0,498.0
49380,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,49,MAINE ET LOIRE,380,Vaulandry,202.0,41.0,3.0,62.0,96.0
52379,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,52,HAUTE MARNE,379,Pautaines-Augeville,28.0,6.0,1.0,3.0,18.0
69025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,69,RHONE,025,Bourg-de-Thizy,1762.0,382.0,26.0,489.0,865.0
69041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,69,RHONE,041,La Chapelle-de-Mardore,181.0,13.0,3.0,42.0,123.0
69128,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,69,RHONE,128,Mardore,416.0,57.0,4.0,125.0,230.0
69129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,69,RHONE,129,Marnand,467.0,63.0,8.0,101.0,295.0
69144,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,69,RHONE,144,Nuelles,505.0,46.0,9.0,153.0,297.0
75056,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,75,PARIS,056,Paris,1253322.0,248755.0,12093.0,506594.0,485880.0
79353,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79,DEUX SEVRES,353,Vitré,452.0,83.0,6.0,213.0,150.0
79356,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,79,DEUX SEVRES,356,Voultegon,390.0,47.0,5.0,126.0,212.0
88282,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,88,VOSGES,282,Le Magny,28.0,9.0,0.0,5.0,14.0

# Biggest difference : Paris is split in 20 arrondissements in the diploma DB